// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfvvHcBsN_5FbBWYPbKKBmYZ8bVgSRz8',
    appId: '1:281366824471:web:491286d35e8b494627fe52',
    messagingSenderId: '281366824471',
    projectId: 'migration-fd7b4',
    authDomain: 'migration-fd7b4.firebaseapp.com',
    storageBucket: 'migration-fd7b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdntk0_PVHs0sPbNbPyqb9-4f17VKaPk',
    appId: '1:281366824471:android:94a453e142a9b41827fe52',
    messagingSenderId: '281366824471',
    projectId: 'migration-fd7b4',
    storageBucket: 'migration-fd7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdyXoV9y8SQXczKEkqnwg-O4jraW_VCY',
    appId: '1:281366824471:ios:f0b2a3867319828927fe52',
    messagingSenderId: '281366824471',
    projectId: 'migration-fd7b4',
    storageBucket: 'migration-fd7b4.firebasestorage.app',
    iosBundleId: 'com.example.alrayaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdyXoV9y8SQXczKEkqnwg-O4jraW_VCY',
    appId: '1:281366824471:ios:f0b2a3867319828927fe52',
    messagingSenderId: '281366824471',
    projectId: 'migration-fd7b4',
    storageBucket: 'migration-fd7b4.firebasestorage.app',
    iosBundleId: 'com.example.alrayaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpfvvHcBsN_5FbBWYPbKKBmYZ8bVgSRz8',
    appId: '1:281366824471:web:5069999f01046c2b27fe52',
    messagingSenderId: '281366824471',
    projectId: 'migration-fd7b4',
    authDomain: 'migration-fd7b4.firebaseapp.com',
    storageBucket: 'migration-fd7b4.firebasestorage.app',
  );

}